### PR TITLE
Customisation of row level action based on row content

### PR DESCRIPTION
**Pull request by subrahmanyam-mahaswami**
Customisation of row level action based on row content
1. The action class need to implement IOptionalRowAction interface and override isApplicableForRow method.
2. The method receives a parameter which is primary key of the row.
3. This method returns TRUE or FALSE, which shows/hides action on each row.

### CODE REVIEW

**Review by subrahmanyamjanapamula — COMMENTED** [review]
public boolean isApplicableForRow(Object primaryKey) {
            boolean displayAction = false;
            //condition to hide or show action
            return displayAction;
     }

**Comment by javierpaniza** [comment]
I added as a feature request to include it for 6.5:
https://openxava.org/XavaProjects/o/OpenXava/m/Issue?detail=ff808081766801ee0176b5e6f3790021

When I'll revise the code I will give you feedback

**Comment by javierpaniza** [comment]
Finally I revised the code. Following a convention for method naming and using instrospection for looking for the method is a correct way to design software, however when you extends and existing framework you have to be coherent with the already way of working. Coherence helps developer to learn faster how to use the framework.

In OpenXava we use interfaces to specify special type of actions or special features of actions, look at the pagacke org.openxava.actions to see the list of arlready existing interface. That is you should create a IOptionalRowAction (or so) with the method isApplicableForRow() and modify the listEditor.jsp to use that interface.

Do the modification and I'll merge your code.

**Comment by subrahmanyam-mahaswami** [comment]
Thank you for the feedback. As you described, I have added IOptionalRowAction interface and changed the listEditor.jsp

**Comment by javierpaniza** [comment]
Fantastic! I'll revise the code and do the merge if possible, as soon as possible. Thanks

**Comment by javierpaniza** [comment]
I revised you code and found that it does not even compile. I get this error:

An error occurred at line: [370] in the jsp file: [/xava/editors/listEditor.jsp]
IOptionalRowAction cannot be resolved to a type
367: 			if(tempAction.getQualifiedName().equals(rowAction)) {
368: 			   Class className = Class.forName(tempAction.getClassName());
369: 				boolean methodExists = false;
370: 				if (IOptionalRowAction.class.isAssignableFrom(className)) {
371: 					Method m = className.getDeclaredMethod("isApplicableForRow", Object.class);
372: 					methodExists = true;
373: 					boolean rowAllowsAction = (boolean) m.invoke(className.newInstance(), map.get("id"));

So you have not tried the code. You should try the code and asure it works before submit it.

I also found a detail to improve. Once you use an interface you can reduce the amount of instrospection code you use. That is, you could instance the object, cast to IOptionalRowAction and call directly the method. Like this:

IOptionRowAction optionalAction = (IOptionRowAction) className.newInstance();
if (optionalAction.isisApplicableForRow(row)) { // With no instrospection

In this way if the IOptionRowAction signature changes the compiler will advice us it there is some error, so it's better than instrospection. Although it's only a minor improvement.

Moroever, I found a important fault. You send map.get("id"). What is the entity has no a property called id? The id property could be named oid, or number, or even be a composite key. The code only works with your code, where possibly all entities extends Identifiable, or so. 

So, at least you have to fix listEditor.jsp in order it compiles and don't send map.get("id"), you can send the complete map or the entity (use MapFacade.findEntity()). The later option makes the IOptionalRowAction easier to use. And over all, try the code before do the push.

**Comment by subrahmanyam-mahaswami** [comment]
Thank you for your guidance and feedback, I appreciate your patience. I'll come back to you after reviewing it.

**Pull request closed without merging**
